import type { Carousel } from "./types";

// Principles mined from Shaiden's ebook "The Game of Life" — Volume I.
export const gameOfLife1: Carousel = {
  slug: "game-of-life-i",
  title: "The Game of Life · I",
  topic: "The Game of Life",
  date: "2026-06-30",
  summary:
    "Nine principles from The Game of Life — on freedom, purpose, integrity, and refusing to play someone else's game.",
  caption:
    "Nine ideas from The Game of Life that changed how I play. Most people never realize they're free to play their own game at all. Swipe through — then save the one you needed to hear. Which hit hardest? 👇",
  hashtags: ["thegameoflife", "purpose", "integrity", "selfactualization", "playyourowngame"],
  slides: [
    {
      kind: "cover",
      eyebrow: "Ebook · Vol. I",
      title: "The Game of Life",
      glyph: "G",
      subtitle: "Nine principles for playing a game worth winning.",
    },
    {
      kind: "principle",
      n: "01",
      eyebrow: "Freedom",
      text: "If life is a game, the only way to lose is to spend it playing someone else's.",
      emphasis: "playing someone else's",
      elaboration: "Most people never realize they're free to play at all, so they chase a scoreboard they never chose. You're allowed to write your own.",
    },
    {
      kind: "principle",
      n: "02",
      eyebrow: "Identity",
      text: "You are not a passenger in reality. You are one of its architects.",
      emphasis: "one of its architects",
      elaboration: "Your job is to feel the contrast, then design and redesign reality to make it better. You shape the game — you don't just survive it.",
    },
    {
      kind: "principle",
      n: "03",
      eyebrow: "Purpose",
      text: "Your purpose isn't invented, it's excavated. And the dig site is your own life.",
      emphasis: "it's excavated",
      elaboration: "We solve most powerfully what we've personally felt. Your purpose lives where your deepest 'this shouldn't be this way' meets your ability to fix it.",
    },
    {
      kind: "principle",
      n: "04",
      eyebrow: "Purpose",
      text: "Your pain points aren't just wounds — they're assignments.",
      emphasis: "they're assignments",
      elaboration: "The contrast you've lived handed you a private map of what's broken and what should exist instead. Don't run from what hurt you. Study it.",
    },
    {
      kind: "principle",
      n: "05",
      eyebrow: "Integrity",
      text: "You can fool the whole world, but you cannot fool the person in the glass.",
      emphasis: "cannot fool the person in the glass",
      elaboration: "The only judge whose verdict truly matters is the one staring back in the mirror. That's the opinion you have to live inside, every single day.",
    },
    {
      kind: "principle",
      n: "06",
      eyebrow: "Integrity",
      text: "Integrity is closing the gap between who you know you are and how you actually live.",
      emphasis: "who you know you are",
      elaboration: "Every time you know you could do something and don't, you break a promise to yourself. Enough of those and you stop trusting your own word.",
    },
    {
      kind: "principle",
      n: "07",
      eyebrow: "Mindset",
      text: "Drop the comparison. Your only real competition is who you were yesterday.",
      emphasis: "who you were yesterday",
      elaboration: "Someone will always have started ahead, and someone behind. The game isn't won from the best square — it's won by players who keep moving.",
    },
    {
      kind: "principle",
      n: "08",
      eyebrow: "Money",
      text: "You don't chase money. Money is the receipt for value delivered, not the prize.",
      emphasis: "the receipt for value delivered",
      elaboration: "Create something genuinely valuable for real people and money flows back as the natural echo. Aim at purpose and value, let the abundance follow.",
    },
    {
      kind: "principle",
      n: "09",
      eyebrow: "Environment",
      text: "You are largely the sum of your inputs — and most of them are yours to choose.",
      emphasis: "the sum of your inputs",
      elaboration: "If you want better outputs, don't grind harder on the output — upgrade the inputs. A well-chosen environment does the heavy lifting for you.",
    },
    {
      kind: "cta",
      eyebrow: "Vol. II next",
      title: "This is half of it.",
      body: "Nine more principles from The Game of Life in Volume II. Follow so you catch it.",
      handle: "@shaiden",
    },
  ],
};
