import type { Carousel } from "./types";

// Principles mined from Shaiden's ebook "The Game of Life" — Volume II.
export const gameOfLife2: Carousel = {
  slug: "game-of-life-ii",
  title: "The Game of Life · II",
  topic: "The Game of Life",
  date: "2026-06-30",
  summary:
    "Nine more principles from The Game of Life — on magnetism, meaning, the inherited 'shoulds', and turning up the volume on who you are.",
  caption:
    "Part two of the principles from The Game of Life. The default path quietly trades your most alive decades for a permission slip to live. Here's the other way. Swipe, save, and turn up the volume. 👇",
  hashtags: ["thegameoflife", "selfactualization", "meaning", "freedom", "becoming"],
  slides: [
    {
      kind: "cover",
      eyebrow: "Ebook · Vol. II",
      title: "The Game of Life",
      glyph: "G",
      subtitle: "Nine more principles — picking up where Vol. I left off.",
    },
    {
      kind: "principle",
      n: "10",
      eyebrow: "Identity",
      text: "When you live in your purpose and integrity, you stop chasing and start attracting.",
      emphasis: "stop chasing and start attracting",
      elaboration: "Integrity becomes self-respect, then confidence, then a magnetism you cannot fake. Self-actualization is the most generous signal you can send.",
    },
    {
      kind: "principle",
      n: "11",
      eyebrow: "Fulfillment",
      text: "The fulfilled life isn't the one with the most pleasure — it's the one with the most meaning.",
      emphasis: "the most meaning",
      elaboration: "Pleasure is a sugar rush; fulfillment is nourishment. Hedonism is a trap precisely because it imitates the real thing while delivering the opposite.",
    },
    {
      kind: "principle",
      n: "12",
      eyebrow: "Growth",
      text: "You can't think your way out of a worldview you've never stepped outside of.",
      emphasis: "never stepped outside of",
      elaboration: "Most of who you are isn't chosen — it's absorbed. Leave your bubble often enough that you never confuse it for the whole world again.",
    },
    {
      kind: "principle",
      n: "13",
      eyebrow: "Freedom",
      text: "A lot of what you think you should do is just someone else's fear wearing your name.",
      emphasis: "someone else's fear wearing your name",
      elaboration: "You inherited a voice from parents, teachers, culture, algorithms. Keep the shoulds that survive scrutiny, delete the rest — that freed space is your real life.",
    },
    {
      kind: "principle",
      n: "14",
      eyebrow: "Action",
      text: "Clarity is worthless until it touches the world. The bridge is a small, honest first step taken now.",
      emphasis: "a small, honest first step",
      elaboration: "The gap between people who find themselves and people who live it is the willingness to start before they feel ready. A life is a stack of unqualified first steps.",
    },
    {
      kind: "principle",
      n: "15",
      eyebrow: "Love",
      text: "You can win every other level and still feel poor if you skip this one.",
      emphasis: "still feel poor if you skip",
      elaboration: "Love is slow, messy, and impossible to optimize — which is probably exactly why it's the deepest. Don't let the measurable crowd out the meaningful.",
    },
    {
      kind: "principle",
      n: "16",
      eyebrow: "Fulfillment",
      text: "If you're not enjoying the game, you're probably playing the wrong one. Change it.",
      emphasis: "playing the wrong one",
      elaboration: "Don't get so serious about playing well that you forget the point: you get to play at all. The hard parts should feel like a game you love, not a sentence.",
    },
    {
      kind: "principle",
      n: "17",
      eyebrow: "Freedom",
      text: "The default path trades your most alive decades for a permission slip to live — that may never arrive.",
      emphasis: "your most alive decades",
      elaboration: "It rewards fitting in over finding out. By the time most people look successful, they've forgotten how to ask their own questions.",
    },
    {
      kind: "principle",
      n: "18",
      eyebrow: "Identity",
      text: "Self-actualization is turning up the volume on who you really are.",
      emphasis: "turning up the volume",
      elaboration: "Where you dim, shrink, or perform a smaller version of yourself to fit in, you make yourself harder to find. Get louder, and the right people reach you.",
    },
    {
      kind: "cta",
      eyebrow: "Your turn",
      title: "Which one are you living?",
      body: "Save this, pick the principle you most need right now, and act on it this week.",
      handle: "@shaiden",
    },
  ],
};
