import type { Carousel } from "./types";

// Principles mined from Shaiden's ebook "Living in Bali".
export const livingInBali: Carousel = {
  slug: "living-in-bali",
  title: "Living in Bali",
  topic: "Living in Bali",
  date: "2026-06-30",
  summary:
    "Fourteen principles from Living in Bali — on environment, freedom, and the geography of building a better default day.",
  caption:
    "Bali was the single biggest input I ever changed on purpose. These fourteen principles from Living in Bali aren't about visas and cafes — they're about designing the place you wake up in. Swipe 👇",
  hashtags: ["livinginbali", "bali", "environmentdesign", "freedom", "expatlife"],
  slides: [
    {
      kind: "cover",
      eyebrow: "Ebook · Principles",
      title: "Living in Bali",
      glyph: "B",
      subtitle: "Fourteen principles on choosing where — and how — you live.",
    },
    {
      kind: "principle",
      n: "01",
      eyebrow: "Environment",
      text: "Bali was the single biggest input I ever changed on purpose.",
      emphasis: "the single biggest input",
      elaboration: "You are largely the sum of your inputs — your people, your habits, your body, the place you wake up in. Change the place and you change the default day.",
    },
    {
      kind: "principle",
      n: "02",
      eyebrow: "Lifestyle",
      text: "Bali rewards people who come to build a life, and quietly punishes people who come to run from one.",
      emphasis: "build a life",
      elaboration: "The island sells itself as an endless holiday, but the ones who thrive use it as a base to do focused work and live well. Come to build, not to escape.",
    },
    {
      kind: "principle",
      n: "03",
      eyebrow: "Freedom",
      text: "A low cost of living that buys back your time is the whole game.",
      emphasis: "buys back your time",
      elaboration: "Cheap living isn't about being cheap — it's about reclaiming the hours most people sell off just to survive. That reclaimed time is what you came for.",
    },
    {
      kind: "principle",
      n: "04",
      eyebrow: "Lifestyle",
      text: "Treat your first stint as a test, not a tattoo.",
      emphasis: "a test, not a tattoo",
      elaboration: "The island sells itself on a two-week trip — you want to know how it feels on a normal Tuesday. Live like you actually live, work hours and all, then commit.",
    },
    {
      kind: "principle",
      n: "05",
      eyebrow: "Wellness",
      text: "Bali is a place to calm your nervous system and go inward, not to chase the next hit of dopamine.",
      emphasis: "go inward",
      elaboration: "The endless party and bottomless brunch you can find anywhere in the world. Skip it and let the real island reach something the beach club never could.",
    },
    {
      kind: "principle",
      n: "06",
      eyebrow: "Environment",
      text: "Where you live is the input that colors every day.",
      emphasis: "colors every day",
      elaboration: "Not the island — the street. Find the exact corner you want to wake up on before you commit a year. Calm and chaos can be a ten-minute ride apart.",
    },
    {
      kind: "principle",
      n: "07",
      eyebrow: "Intention",
      text: "Before the logistics, be honest about the why.",
      emphasis: "be honest about the why",
      elaboration: "You're not on holiday — you're choosing an input that will shape years of your life. The people who love a place long-term tested it slow, then committed.",
    },
    {
      kind: "principle",
      n: "08",
      eyebrow: "Freedom",
      text: "The life you want is usually closer — and simpler to reach — than you think.",
      emphasis: "closer — and simpler to reach",
      elaboration: "The whole thing feels like a wall of red tape until someone lays it out whole. Then it's a handful of things, done once, in the right order — and you're free.",
    },
    {
      kind: "principle",
      n: "09",
      eyebrow: "Community",
      text: "Pick three anchors — a gym, a co-working spot, one sport — and just keep showing up.",
      emphasis: "keep showing up",
      elaboration: "You don't network your way into a community, you anchor into one. The same faces become your people within weeks. Bali rewards consistency.",
    },
    {
      kind: "principle",
      n: "10",
      eyebrow: "Respect",
      text: "This place is not a backdrop for your highlight reel.",
      emphasis: "not a backdrop",
      elaboration: "The culture is the entire reason the island feels the way it does. You're a guest inside a living, daily devotion — move through it with humility.",
    },
    {
      kind: "principle",
      n: "11",
      eyebrow: "Respect",
      text: "If you're going to walk all over the place and its people — why did you come here at all?",
      emphasis: "why did you come here at all",
      elaboration: "You crossed the world for its calm, its people, its spirit. Trampling that is choosing to destroy the exact thing you came to find.",
    },
    {
      kind: "principle",
      n: "12",
      eyebrow: "Simplicity",
      text: "The cheapest visa is the correct one. Everything else has a hidden bill.",
      emphasis: "the correct one",
      elaboration: "Doing it properly is a rounding error next to the cost of doing it wrong. Match your life to reality and the whole thing gets cheaper and calmer at once.",
    },
    {
      kind: "principle",
      n: "13",
      eyebrow: "Patience",
      text: "For your first year, lease, don't buy.",
      emphasis: "lease, don't buy",
      elaboration: "Commit capital only once you know exactly which street you want to wake up on. Learn the micro-areas in real life before you pour money into one.",
    },
    {
      kind: "principle",
      n: "14",
      eyebrow: "Respect",
      text: "Learn even five words of the local language, and watch how differently the island treats you.",
      emphasis: "how differently the island treats you",
      elaboration: "The smallest effort to meet people where they are changes everything that comes back to you. Respect, offered first, is the cheat code.",
    },
    {
      kind: "cta",
      eyebrow: "Your turn",
      title: "Where do you wake up?",
      body: "Your environment is an input you're allowed to choose. Save this if you've been thinking about changing yours.",
      handle: "@shaiden",
    },
  ],
};
